// Generated by ReScript, PLEASE EDIT WITH CARE


function isIntermediate(ch) {
  switch (ch) {
    case "#" :
    case "(" :
    case ")" :
    case ";" :
    case "?" :
    case "[" :
    case "]" :
      return true;
    default:
      return false;
  }
}

function isParameter(ch) {
  switch (ch) {
    case "0" :
    case "1" :
    case "2" :
    case "3" :
    case "4" :
    case "5" :
    case "6" :
    case "7" :
    case "8" :
    case "9" :
    case ";" :
      return true;
    default:
      return false;
  }
}

function isFinal(ch) {
  switch (ch) {
    case "0" :
    case "1" :
    case "2" :
    case "3" :
    case "4" :
    case "5" :
    case "6" :
    case "7" :
    case "8" :
    case "9" :
    case "<" :
    case "=" :
    case ">" :
    case "A" :
    case "B" :
    case "C" :
    case "D" :
    case "E" :
    case "F" :
    case "G" :
    case "H" :
    case "I" :
    case "J" :
    case "K" :
    case "L" :
    case "M" :
    case "N" :
    case "O" :
    case "P" :
    case "R" :
    case "S" :
    case "T" :
    case "U" :
    case "V" :
    case "W" :
    case "X" :
    case "Y" :
    case "Z" :
    case "a" :
    case "c" :
    case "f" :
    case "n" :
    case "q" :
    case "u" :
    case "y" :
    case "~" :
      return true;
    default:
      return false;
  }
}

function ansiState(state, ch) {
  switch (state) {
    case 1 :
      switch (ch) {
        case "\x1B" :
          return 3;
        case "\x07" :
        case "\x9C" :
          return 4;
        default:
          if (isIntermediate(ch) || isParameter(ch) || !isFinal(ch)) {
            return 2;
          } else {
            return 4;
          }
      }
    case 2 :
      switch (ch) {
        case "\x1B" :
          return 3;
        case "\x07" :
        case "\x9C" :
          return 4;
        default:
          if (isFinal(ch)) {
            return 4;
          } else {
            return 2;
          }
      }
    case 3 :
      if (ch === "\\") {
        return 4;
      } else {
        return 2;
      }
    case 0 :
    case 4 :
      switch (ch) {
        case "\x1B" :
        case "\x9B" :
          return 1;
        default:
          return 0;
      }
  }
}

export {
  ansiState,
}
/* No side effect */
