// Generated by ReScript, PLEASE EDIT WITH CARE


function isIntermediate(ch) {
  if (ch >= 60) {
    if (ch > 93 || ch < 91) {
      return ch === 63;
    } else {
      return ch !== 92;
    }
  } else if (ch >= 40) {
    return ch > 58 || ch < 42;
  } else {
    return ch === 35;
  }
}

function isParameter(ch) {
  if (ch >= 58) {
    return ch === 59;
  } else {
    return ch >= 48;
  }
}

function isFinal(ch) {
  if (ch < 63) {
    if (ch >= 58) {
      return ch >= 60;
    } else {
      return ch >= 48;
    }
  }
  if (ch < 81) {
    return ch >= 65;
  }
  if (ch >= 127) {
    return false;
  }
  switch (ch) {
    case 81 :
    case 91 :
    case 92 :
    case 93 :
    case 94 :
    case 95 :
    case 96 :
    case 98 :
    case 100 :
    case 101 :
    case 103 :
    case 104 :
    case 105 :
    case 106 :
    case 107 :
    case 108 :
    case 109 :
    case 111 :
    case 112 :
    case 114 :
    case 115 :
    case 116 :
    case 118 :
    case 119 :
    case 120 :
    case 122 :
    case 123 :
    case 124 :
    case 125 :
      return false;
    case 82 :
    case 83 :
    case 84 :
    case 85 :
    case 86 :
    case 87 :
    case 88 :
    case 89 :
    case 90 :
    case 97 :
    case 99 :
    case 102 :
    case 110 :
    case 113 :
    case 117 :
    case 121 :
    case 126 :
      return true;
  }
}

function ansiState(state, ch) {
  switch (state) {
    case 1 :
      if (ch > 155 || ch < 8) {
        if (!(ch > 156 || ch < 7)) {
          return 4;
        }
        
      } else if (ch === 27) {
        return 3;
      }
      if (isIntermediate(ch) || isParameter(ch) || !isFinal(ch)) {
        return 2;
      } else {
        return 4;
      }
    case 2 :
      if (ch > 155 || ch < 8) {
        if ((ch > 156 || ch < 7) && !isFinal(ch)) {
          return 2;
        } else {
          return 4;
        }
      } else if (ch !== 27) {
        if (isFinal(ch)) {
          return 4;
        } else {
          return 2;
        }
      } else {
        return 3;
      }
    case 3 :
      if (ch !== 92) {
        return 2;
      } else {
        return 4;
      }
    case 0 :
    case 4 :
      if (ch !== 27 && ch !== 155) {
        return 0;
      } else {
        return 1;
      }
  }
}

export {
  ansiState,
}
/* No side effect */
